package com.example.mapper.user_perfect;

import com.example.pojo.UserPerfect;
import com.example.pojo.UserPerfectExample;
import com.example.pojo.UserPerfectWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserPerfectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    int countByExample(UserPerfectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    int deleteByExample(UserPerfectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    int insert(UserPerfectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    int insertSelective(UserPerfectWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    List<UserPerfectWithBLOBs> selectByExampleWithBLOBs(UserPerfectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    List<UserPerfect> selectByExample(UserPerfectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") UserPerfectWithBLOBs record, @Param("example") UserPerfectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    int updateByExampleWithBLOBs(@Param("record") UserPerfectWithBLOBs record, @Param("example") UserPerfectExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") UserPerfect record, @Param("example") UserPerfectExample example);
}