package com.example.mapper.train;

import com.example.pojo.Train;
import com.example.pojo.TrainExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TrainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int countByExample(TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int deleteByExample(TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer trainid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int insert(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int insertSelective(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    List<Train> selectByExample(TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    Train selectByPrimaryKey(Integer trainid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Train record, @Param("example") TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Train record, @Param("example") TrainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Train record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Train record);
}