package com.example.pojo;

import java.util.Date;

public class Business {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.groupsid
     *
     * @mbggenerated
     */
    private Integer groupsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.toTime
     *
     * @mbggenerated
     */
    private Date totime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.outTime
     *
     * @mbggenerated
     */
    private Date outtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.useTime
     *
     * @mbggenerated
     */
    private Byte usetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column business.isuse
     *
     * @mbggenerated
     */
    private Byte isuse;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated
     */
    public Business(Integer groupsid, Integer userid, Date totime, Date outtime, Byte usetime, Byte isuse) {
        this.groupsid = groupsid;
        this.userid = userid;
        this.totime = totime;
        this.outtime = outtime;
        this.usetime = usetime;
        this.isuse = isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table business
     *
     * @mbggenerated
     */
    public Business() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.groupsid
     *
     * @return the value of business.groupsid
     *
     * @mbggenerated
     */
    public Integer getGroupsid() {
        return groupsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.groupsid
     *
     * @param groupsid the value for business.groupsid
     *
     * @mbggenerated
     */
    public void setGroupsid(Integer groupsid) {
        this.groupsid = groupsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.userid
     *
     * @return the value of business.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.userid
     *
     * @param userid the value for business.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.toTime
     *
     * @return the value of business.toTime
     *
     * @mbggenerated
     */
    public Date getTotime() {
        return totime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.toTime
     *
     * @param totime the value for business.toTime
     *
     * @mbggenerated
     */
    public void setTotime(Date totime) {
        this.totime = totime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.outTime
     *
     * @return the value of business.outTime
     *
     * @mbggenerated
     */
    public Date getOuttime() {
        return outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.outTime
     *
     * @param outtime the value for business.outTime
     *
     * @mbggenerated
     */
    public void setOuttime(Date outtime) {
        this.outtime = outtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.useTime
     *
     * @return the value of business.useTime
     *
     * @mbggenerated
     */
    public Byte getUsetime() {
        return usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.useTime
     *
     * @param usetime the value for business.useTime
     *
     * @mbggenerated
     */
    public void setUsetime(Byte usetime) {
        this.usetime = usetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column business.isuse
     *
     * @return the value of business.isuse
     *
     * @mbggenerated
     */
    public Byte getIsuse() {
        return isuse;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column business.isuse
     *
     * @param isuse the value for business.isuse
     *
     * @mbggenerated
     */
    public void setIsuse(Byte isuse) {
        this.isuse = isuse;
    }
}