package com.example.pojo;

import java.util.Date;

public class Groups {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groupsid
     *
     * @mbggenerated
     */
    private Integer groupsid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groupsname
     *
     * @mbggenerated
     */
    private String groupsname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groupsinfo
     *
     * @mbggenerated
     */
    private String groupsinfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.groupsowner
     *
     * @mbggenerated
     */
    private Integer groupsowner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.createTime
     *
     * @mbggenerated
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.workTime
     *
     * @mbggenerated
     */
    private Date worktime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column groups.endTime
     *
     * @mbggenerated
     */
    private Date endtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated
     */
    public Groups(Integer groupsid, String groupsname, String groupsinfo, Integer groupsowner, Date createtime, Date worktime, Date endtime) {
        this.groupsid = groupsid;
        this.groupsname = groupsname;
        this.groupsinfo = groupsinfo;
        this.groupsowner = groupsowner;
        this.createtime = createtime;
        this.worktime = worktime;
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table groups
     *
     * @mbggenerated
     */
    public Groups() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groupsid
     *
     * @return the value of groups.groupsid
     *
     * @mbggenerated
     */
    public Integer getGroupsid() {
        return groupsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groupsid
     *
     * @param groupsid the value for groups.groupsid
     *
     * @mbggenerated
     */
    public void setGroupsid(Integer groupsid) {
        this.groupsid = groupsid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groupsname
     *
     * @return the value of groups.groupsname
     *
     * @mbggenerated
     */
    public String getGroupsname() {
        return groupsname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groupsname
     *
     * @param groupsname the value for groups.groupsname
     *
     * @mbggenerated
     */
    public void setGroupsname(String groupsname) {
        this.groupsname = groupsname == null ? null : groupsname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groupsinfo
     *
     * @return the value of groups.groupsinfo
     *
     * @mbggenerated
     */
    public String getGroupsinfo() {
        return groupsinfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groupsinfo
     *
     * @param groupsinfo the value for groups.groupsinfo
     *
     * @mbggenerated
     */
    public void setGroupsinfo(String groupsinfo) {
        this.groupsinfo = groupsinfo == null ? null : groupsinfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.groupsowner
     *
     * @return the value of groups.groupsowner
     *
     * @mbggenerated
     */
    public Integer getGroupsowner() {
        return groupsowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.groupsowner
     *
     * @param groupsowner the value for groups.groupsowner
     *
     * @mbggenerated
     */
    public void setGroupsowner(Integer groupsowner) {
        this.groupsowner = groupsowner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.createTime
     *
     * @return the value of groups.createTime
     *
     * @mbggenerated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.createTime
     *
     * @param createtime the value for groups.createTime
     *
     * @mbggenerated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.workTime
     *
     * @return the value of groups.workTime
     *
     * @mbggenerated
     */
    public Date getWorktime() {
        return worktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.workTime
     *
     * @param worktime the value for groups.workTime
     *
     * @mbggenerated
     */
    public void setWorktime(Date worktime) {
        this.worktime = worktime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column groups.endTime
     *
     * @return the value of groups.endTime
     *
     * @mbggenerated
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column groups.endTime
     *
     * @param endtime the value for groups.endTime
     *
     * @mbggenerated
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }
}