package com.example.pojo;

public class Take {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take.groupid
     *
     * @mbggenerated
     */
    private Integer groupid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take.fromTrainld
     *
     * @mbggenerated
     */
    private Integer fromtrainld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take.toTrainld
     *
     * @mbggenerated
     */
    private Integer totrainld;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take.pay
     *
     * @mbggenerated
     */
    private Integer pay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take.ispay
     *
     * @mbggenerated
     */
    private Integer ispay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column take.payType
     *
     * @mbggenerated
     */
    private Byte paytype;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table take
     *
     * @mbggenerated
     */
    public Take(Integer groupid, Integer userid, Integer fromtrainld, Integer totrainld, Integer pay, Integer ispay, Byte paytype) {
        this.groupid = groupid;
        this.userid = userid;
        this.fromtrainld = fromtrainld;
        this.totrainld = totrainld;
        this.pay = pay;
        this.ispay = ispay;
        this.paytype = paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table take
     *
     * @mbggenerated
     */
    public Take() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take.groupid
     *
     * @return the value of take.groupid
     *
     * @mbggenerated
     */
    public Integer getGroupid() {
        return groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take.groupid
     *
     * @param groupid the value for take.groupid
     *
     * @mbggenerated
     */
    public void setGroupid(Integer groupid) {
        this.groupid = groupid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take.userid
     *
     * @return the value of take.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take.userid
     *
     * @param userid the value for take.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take.fromTrainld
     *
     * @return the value of take.fromTrainld
     *
     * @mbggenerated
     */
    public Integer getFromtrainld() {
        return fromtrainld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take.fromTrainld
     *
     * @param fromtrainld the value for take.fromTrainld
     *
     * @mbggenerated
     */
    public void setFromtrainld(Integer fromtrainld) {
        this.fromtrainld = fromtrainld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take.toTrainld
     *
     * @return the value of take.toTrainld
     *
     * @mbggenerated
     */
    public Integer getTotrainld() {
        return totrainld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take.toTrainld
     *
     * @param totrainld the value for take.toTrainld
     *
     * @mbggenerated
     */
    public void setTotrainld(Integer totrainld) {
        this.totrainld = totrainld;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take.pay
     *
     * @return the value of take.pay
     *
     * @mbggenerated
     */
    public Integer getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take.pay
     *
     * @param pay the value for take.pay
     *
     * @mbggenerated
     */
    public void setPay(Integer pay) {
        this.pay = pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take.ispay
     *
     * @return the value of take.ispay
     *
     * @mbggenerated
     */
    public Integer getIspay() {
        return ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take.ispay
     *
     * @param ispay the value for take.ispay
     *
     * @mbggenerated
     */
    public void setIspay(Integer ispay) {
        this.ispay = ispay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column take.payType
     *
     * @return the value of take.payType
     *
     * @mbggenerated
     */
    public Byte getPaytype() {
        return paytype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column take.payType
     *
     * @param paytype the value for take.payType
     *
     * @mbggenerated
     */
    public void setPaytype(Byte paytype) {
        this.paytype = paytype;
    }
}