package com.example.pojo;

public class Train {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.trainid
     *
     * @mbggenerated
     */
    private Integer trainid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.lineNumber
     *
     * @mbggenerated
     */
    private String linenumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.stationNumber
     *
     * @mbggenerated
     */
    private Integer stationnumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.stationName
     *
     * @mbggenerated
     */
    private String stationname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.lastStation
     *
     * @mbggenerated
     */
    private Integer laststation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.lastStationTime
     *
     * @mbggenerated
     */
    private Integer laststationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.nextStation
     *
     * @mbggenerated
     */
    private Integer nextstation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.nextStationTime
     *
     * @mbggenerated
     */
    private Integer nextstationtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column train.transferStation
     *
     * @mbggenerated
     */
    private Integer transferstation;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    public Train(Integer trainid, String linenumber, Integer stationnumber, String stationname, Integer laststation, Integer laststationtime, Integer nextstation, Integer nextstationtime, Integer transferstation) {
        this.trainid = trainid;
        this.linenumber = linenumber;
        this.stationnumber = stationnumber;
        this.stationname = stationname;
        this.laststation = laststation;
        this.laststationtime = laststationtime;
        this.nextstation = nextstation;
        this.nextstationtime = nextstationtime;
        this.transferstation = transferstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table train
     *
     * @mbggenerated
     */
    public Train() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.trainid
     *
     * @return the value of train.trainid
     *
     * @mbggenerated
     */
    public Integer getTrainid() {
        return trainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.trainid
     *
     * @param trainid the value for train.trainid
     *
     * @mbggenerated
     */
    public void setTrainid(Integer trainid) {
        this.trainid = trainid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.lineNumber
     *
     * @return the value of train.lineNumber
     *
     * @mbggenerated
     */
    public String getLinenumber() {
        return linenumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.lineNumber
     *
     * @param linenumber the value for train.lineNumber
     *
     * @mbggenerated
     */
    public void setLinenumber(String linenumber) {
        this.linenumber = linenumber == null ? null : linenumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.stationNumber
     *
     * @return the value of train.stationNumber
     *
     * @mbggenerated
     */
    public Integer getStationnumber() {
        return stationnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.stationNumber
     *
     * @param stationnumber the value for train.stationNumber
     *
     * @mbggenerated
     */
    public void setStationnumber(Integer stationnumber) {
        this.stationnumber = stationnumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.stationName
     *
     * @return the value of train.stationName
     *
     * @mbggenerated
     */
    public String getStationname() {
        return stationname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.stationName
     *
     * @param stationname the value for train.stationName
     *
     * @mbggenerated
     */
    public void setStationname(String stationname) {
        this.stationname = stationname == null ? null : stationname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.lastStation
     *
     * @return the value of train.lastStation
     *
     * @mbggenerated
     */
    public Integer getLaststation() {
        return laststation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.lastStation
     *
     * @param laststation the value for train.lastStation
     *
     * @mbggenerated
     */
    public void setLaststation(Integer laststation) {
        this.laststation = laststation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.lastStationTime
     *
     * @return the value of train.lastStationTime
     *
     * @mbggenerated
     */
    public Integer getLaststationtime() {
        return laststationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.lastStationTime
     *
     * @param laststationtime the value for train.lastStationTime
     *
     * @mbggenerated
     */
    public void setLaststationtime(Integer laststationtime) {
        this.laststationtime = laststationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.nextStation
     *
     * @return the value of train.nextStation
     *
     * @mbggenerated
     */
    public Integer getNextstation() {
        return nextstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.nextStation
     *
     * @param nextstation the value for train.nextStation
     *
     * @mbggenerated
     */
    public void setNextstation(Integer nextstation) {
        this.nextstation = nextstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.nextStationTime
     *
     * @return the value of train.nextStationTime
     *
     * @mbggenerated
     */
    public Integer getNextstationtime() {
        return nextstationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.nextStationTime
     *
     * @param nextstationtime the value for train.nextStationTime
     *
     * @mbggenerated
     */
    public void setNextstationtime(Integer nextstationtime) {
        this.nextstationtime = nextstationtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column train.transferStation
     *
     * @return the value of train.transferStation
     *
     * @mbggenerated
     */
    public Integer getTransferstation() {
        return transferstation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column train.transferStation
     *
     * @param transferstation the value for train.transferStation
     *
     * @mbggenerated
     */
    public void setTransferstation(Integer transferstation) {
        this.transferstation = transferstation;
    }
}