package com.example.pojo;

public class UserPerfect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_perfect.userid
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_perfect.useridCard
     *
     * @mbggenerated
     */
    private String useridcard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_perfect.userRealName
     *
     * @mbggenerated
     */
    private String userrealname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_perfect.isAutoPay
     *
     * @mbggenerated
     */
    private Byte isautopay;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_perfect.userEmail
     *
     * @mbggenerated
     */
    private String useremail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_perfect.userSex
     *
     * @mbggenerated
     */
    private String usersex;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    public UserPerfect(Integer userid, String useridcard, String userrealname, Byte isautopay, String useremail, String usersex) {
        this.userid = userid;
        this.useridcard = useridcard;
        this.userrealname = userrealname;
        this.isautopay = isautopay;
        this.useremail = useremail;
        this.usersex = usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    public UserPerfect() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_perfect.userid
     *
     * @return the value of user_perfect.userid
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_perfect.userid
     *
     * @param userid the value for user_perfect.userid
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_perfect.useridCard
     *
     * @return the value of user_perfect.useridCard
     *
     * @mbggenerated
     */
    public String getUseridcard() {
        return useridcard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_perfect.useridCard
     *
     * @param useridcard the value for user_perfect.useridCard
     *
     * @mbggenerated
     */
    public void setUseridcard(String useridcard) {
        this.useridcard = useridcard == null ? null : useridcard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_perfect.userRealName
     *
     * @return the value of user_perfect.userRealName
     *
     * @mbggenerated
     */
    public String getUserrealname() {
        return userrealname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_perfect.userRealName
     *
     * @param userrealname the value for user_perfect.userRealName
     *
     * @mbggenerated
     */
    public void setUserrealname(String userrealname) {
        this.userrealname = userrealname == null ? null : userrealname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_perfect.isAutoPay
     *
     * @return the value of user_perfect.isAutoPay
     *
     * @mbggenerated
     */
    public Byte getIsautopay() {
        return isautopay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_perfect.isAutoPay
     *
     * @param isautopay the value for user_perfect.isAutoPay
     *
     * @mbggenerated
     */
    public void setIsautopay(Byte isautopay) {
        this.isautopay = isautopay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_perfect.userEmail
     *
     * @return the value of user_perfect.userEmail
     *
     * @mbggenerated
     */
    public String getUseremail() {
        return useremail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_perfect.userEmail
     *
     * @param useremail the value for user_perfect.userEmail
     *
     * @mbggenerated
     */
    public void setUseremail(String useremail) {
        this.useremail = useremail == null ? null : useremail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_perfect.userSex
     *
     * @return the value of user_perfect.userSex
     *
     * @mbggenerated
     */
    public String getUsersex() {
        return usersex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_perfect.userSex
     *
     * @param usersex the value for user_perfect.userSex
     *
     * @mbggenerated
     */
    public void setUsersex(String usersex) {
        this.usersex = usersex == null ? null : usersex.trim();
    }
}