package com.example.pojo;

public class UserPerfectWithBLOBs extends UserPerfect {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_perfect.userPhoto
     *
     * @mbggenerated
     */
    private String userphoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_perfect.userFaceImage
     *
     * @mbggenerated
     */
    private String userfaceimage;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    public UserPerfectWithBLOBs(Integer userid, String useridcard, String userrealname, Byte isautopay, String useremail, String usersex, String userphoto, String userfaceimage) {
        super(userid, useridcard, userrealname, isautopay, useremail, usersex);
        this.userphoto = userphoto;
        this.userfaceimage = userfaceimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_perfect
     *
     * @mbggenerated
     */
    public UserPerfectWithBLOBs() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_perfect.userPhoto
     *
     * @return the value of user_perfect.userPhoto
     *
     * @mbggenerated
     */
    public String getUserphoto() {
        return userphoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_perfect.userPhoto
     *
     * @param userphoto the value for user_perfect.userPhoto
     *
     * @mbggenerated
     */
    public void setUserphoto(String userphoto) {
        this.userphoto = userphoto == null ? null : userphoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_perfect.userFaceImage
     *
     * @return the value of user_perfect.userFaceImage
     *
     * @mbggenerated
     */
    public String getUserfaceimage() {
        return userfaceimage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_perfect.userFaceImage
     *
     * @param userfaceimage the value for user_perfect.userFaceImage
     *
     * @mbggenerated
     */
    public void setUserfaceimage(String userfaceimage) {
        this.userfaceimage = userfaceimage == null ? null : userfaceimage.trim();
    }
}